### ISSUE TITLE
Additional type of device control - SSH

### ISSUE THREAD

**Issue by FrostbyteGR** [gilesknap/maaspower#21]
Greetings,

I was wondering, whether an SSH type of device control could be implemented into the project.

Here's a generic example:

```
name: maaspower ssh example
ip_address: <MAASPOWER_LISTEN_IP>
port: <MAASPOWER_LISTEN_PORT>
username: <MAASPOWER_USERNAME>
password: <MAASPOWER_PASSWORD>
devices:
- type: SSH
    name: ge\d+
    ssh-username: <POE_DEVICE_USERNAME>
    ssh-password: <POE_DEVICE_PASSWORD>
    ssh-key: <RSA_KEY_FILE_PATH>
    on: <POE_ON_COMMAND>
    off: <POE_OFF_COMMAND>
    query: <POE_QUERY_COMMAND>
    query_on_regex: <POE_QUERY_ON_REGEX>
    query_off_regex: <POE_QUERY_OFF_REGEX>
```

Here's another example that could possibly work with MikroTik PoE devices (i.e. CRS328-24P-4S+RM):

```
name: maaspower mikrotik ssh example
ip_address: <MAASPOWER_LISTEN_IP>
port: <MAASPOWER_LISTEN_PORT>
username: <MAASPOWER_USERNAME>
password: <MAASPOWER_PASSWORD>
devices:
- type: SSH
    name: ether\d+
    ssh-username: <POE_DEVICE_USERNAME>
    ssh-password: <POE_DEVICE_PASSWORD>
    ssh-key: <RSA_KEY_FILE_PATH>
    on: interface ethernet poe set poe-out=off \g<0>
    off: interface ethernet poe set poe-out=auto-on \g<0>
    query: interface ethernet poe monitor \g<0> once
    query_on_regex: ^[\t ]*poe-out-status:[\t ]+powered-on$
    query_off_regex: ^[\t ]*poe-out-status:[\t ]+(waiting-for-load|disabled)$
```

**NOTE:** `ssh-password` and `ssh-key` arguments should be mutually exclusive?

I believe that right now, the same thing can be achieved via `type: CommandLine` like this:

```
  - type: CommandLine
    name: ether\d+
    on: maaspower_ssh_mikrotik.sh \g<0> on
    off: maaspower_ssh_mikrotik.sh \g<0> off
    query: maaspower_ssh_mikrotik.sh \g<0> check
    query_on_regex: ^powered-on$
    query_off_regex: ^powered-off$
```

And a `maaspower_ssh_mikrotik.sh` like this:

```
#!/bin/sh

# Configured variables
mtAddress=<MIKROTIK_ADDRESS>
mtUsername=<MIKROTIK_USERNAME>
mtPrivateKey=<MIKROTIK_SSH_KEY>
mtInterfacePrefix='ether'

# SSH command
sshCmd="ssh -i $mtPrivateKey $mtUsername@$mtAddress"

# MikroTik PoE commands
poeOnCmd="$sshCmd interface ethernet poe set poe-out=auto-on $1"
poeOffCmd="$sshCmd interface ethernet poe set poe-out=off $1"
poeCheckCmd="$sshCmd interface ethernet poe monitor $1 once"

# Usage helper function
usage() {
cat << EOF
Usage:
$0 <interface> <on|off|check>
Example: $0 ge0 check
EOF
exit 3
}

# Validate user-supplied arguments
[  $# -eq 2 ] && [ -z $(echo $1 | grep -Ev "^$mtInterfacePrefix[0-9]+$") ] || usage
case $2 in
        on) eval $poeOnCmd ;;
        off) eval $poeOffCmd ;;
        check) eval $poeCheckCmd | grep -Eo 'poe-out-status:[\t ]*[a-z\-]+' | awk '{print $2}' | sed -E 's/^(waiting-for-load|disabled)$/powered-off/' ;;
        *) usage ;;
esac
```

Thus, I would consider it as a very low priority kind of request.

Many thanks for your time and efforts on this project!
