### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by antongisli** [gilesknap/maaspower#9]
Wondering if we could extend maaspower so that the _name_ can be extracted into a variable for usage in CLI commands. Example:

- I have 10 servers from 192.168.0.10-192.168.0.20
- I don't want to statically configure them all in maaspower
- I want to call e.g. maaspower/192_168_0_10/power_on and get "192_168_0_10" into a _name_ variable like $name
- I can then pass that variable in my CLI call

So something like (apologies for me mashing languages/yaml):
```
<snip>
devices:
  # These require that the server is running on a machine with USB
  # connection to a power control USB hub and the uhubctl utility installed.
  - type: CommandLine
    name: 192_168_\d{1-3}_\d{1-3}
    on: myscript.sh $name on
    off: myscript.sh $name off
    query: uhubctl -p 1
    query_on_regex: .*power$
    query_off_regex: .*off$
```
